### ISSUE TITLE
Launcher crashes on startup on ubuntu

### ISSUE THREAD

**Issue by woodgern** [jrbudda/Vivecraft_115#21]
Installation runs smoothly through `java -jar vivecraft-1.15.2-jrbudda-NONVR-2-r2-installer.jar`, but when launching minecraft with the "Vivecraft NonVR 1.15.2" profile the launcher closes, and is immediately replaced with  "ERROR Game crashed" (screenshot below).

Checking the launcher logs shows that this exception is causing the crash:
```
[Info: 2020-06-15 23:22:45.456290180: GameCallbacks.cpp(158)] Launcher/launcher (main) Info Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

Any clues as to the cause?

![image](https://user-images.githubusercontent.com/1775468/84715366-37f72b80-af3e-11ea-9cb9-074a13147195.png)

**Comment by Xasin** [comment]
Just got the exact same behaviour on my Debian installation.

I *was* able to successfully run Vivecraft when my Debian installation was Debian 9.
After performing a Dist-Upgrade to Debian 10 however, I started getting this exact screen. It does not occur when playing regular Minecraft without Vivecraft installed.

**Comment by Techjar** [comment]
You're trying to run it on Java 9+, which the current release is not compatible with. This will be fixed in the next release (only on 1.15 and up, 1.12 will still require Java 8). For now install Java 8 and use that for Minecraft.
